# Generated by Django 3.2.25 on 2025-08-14 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.TextField(blank=True)),
                ('usuarios', models.ManyToManyField(db_table='bodega_usuarios', related_name='bodegas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bodega',
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cargo',
            },
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('confirmado', models.BooleanField(default=False)),
                ('bodega_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_entrantes', to='app.bodega')),
                ('bodega_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_salientes', to='app.bodega')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, related_name='envios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'envio',
            },
        ),
        migrations.CreateModel(
            name='ExcelUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='excels/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('padre', models.ForeignKey(blank=True, help_text='Familia padre en caso de ser subcategoría.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfamilias', to='app.familia')),
            ],
            options={
                'verbose_name': 'Familia',
                'verbose_name_plural': 'Familias',
                'db_table': 'familia',
            },
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField()),
                ('total_rows', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('finished_at', models.DateTimeField(blank=True, db_column='finished_at', null=True)),
                ('status', models.CharField(default='processing', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('bodega', models.ForeignKey(db_column='bodega_id', on_delete=django.db.models.deletion.RESTRICT, related_name='import_jobs', to='app.bodega')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.RESTRICT, related_name='import_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Importación',
                'verbose_name_plural': 'Importaciones',
                'db_table': 'import_job',
            },
        ),
        migrations.CreateModel(
            name='PDFUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='pdfs/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras', models.CharField(max_length=20, unique=True)),
                ('centro_costo', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('precio', models.IntegerField()),
                ('familia', models.ForeignKey(help_text='Familia o subfamilia a la que pertenece el producto.', on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='app.familia')),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password_hash', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('id_cargo', models.ForeignKey(db_column='id_cargo', on_delete=django.db.models.deletion.DO_NOTHING, to='app.cargo')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='StockActual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='app.bodega')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='app.producto')),
            ],
            options={
                'unique_together': {('producto', 'bodega')},
            },
        ),
        migrations.CreateModel(
            name='Retiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retiros', to='app.bodega')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='app.producto')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'retiro',
            },
        ),
        migrations.CreateModel(
            name='Pendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('completado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('bodega', models.ForeignKey(db_column='bodega_id', on_delete=django.db.models.deletion.CASCADE, related_name='pendientes', to='app.bodega')),
                ('producto', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.CASCADE, related_name='pendientes', to='app.producto')),
            ],
            options={
                'verbose_name': 'Pendiente',
                'verbose_name_plural': 'Pendientes',
                'db_table': 'pendiente',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('mensaje', models.TextField()),
                ('leido', models.BooleanField(default=False)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('envio', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_envio', to='app.envio')),
                ('pendiente', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_pendiente', to='app.envio')),
                ('stock', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_stock', to='app.stockactual')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'db_table': 'notificacion',
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos', to='app.bodega')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='app.producto')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ingreso',
            },
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('nombre', models.TextField()),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=18)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(default='ok', max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('import_job', models.ForeignKey(db_column='import_job_id', on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='app.importjob')),
                ('producto', models.ForeignKey(blank=True, db_column='producto_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_rows', to='app.producto')),
            ],
            options={
                'verbose_name': 'Fila importada',
                'verbose_name_plural': 'Filas importadas',
                'db_table': 'import_row',
            },
        ),
        migrations.CreateModel(
            name='EnvioDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='app.envio')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producto')),
            ],
            options={
                'db_table': 'envio_detalle',
            },
        ),
    ]
