# Generated by Django 3.2.25 on 2026-01-19 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_notificacion_pendiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='parte',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='stock',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_stock', to='app.stockactual'),
        ),
    ]
