# Generated by Django 5.2.4 on 2025-07-12 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_usuariocargo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuarioCargo',
        ),
    ]
