# Generated by Django 6.0.2 on 2026-03-03 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20260119_1239'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingreso',
            name='id_producto',
        ),
        migrations.RemoveField(
            model_name='ingreso',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='retiro',
            name='id_producto',
        ),
        migrations.RemoveField(
            model_name='retiro',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id_cargo',
        ),
        migrations.AddField(
            model_name='ingreso',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ingresos', to='app.producto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingreso',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ingresos', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='retiro',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='retiros', to='app.producto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='retiro',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='retiros', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='cargo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app.cargo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bodega',
            name='usuarios',
            field=models.ManyToManyField(related_name='bodegas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='envio',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='bodega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='import_jobs', to='app.bodega'),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='import_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='importrow',
            name='import_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='app.importjob'),
        ),
        migrations.AlterField(
            model_name='importrow',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_rows', to='app.producto'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pendiente',
            name='bodega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendientes', to='app.bodega'),
        ),
        migrations.AlterField(
            model_name='pendiente',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendientes', to='app.producto'),
        ),
        migrations.AlterModelTable(
            name='bodega',
            table=None,
        ),
        migrations.AlterModelTable(
            name='cargo',
            table=None,
        ),
        migrations.AlterModelTable(
            name='envio',
            table=None,
        ),
        migrations.AlterModelTable(
            name='enviodetalle',
            table=None,
        ),
        migrations.AlterModelTable(
            name='familia',
            table=None,
        ),
        migrations.AlterModelTable(
            name='importjob',
            table=None,
        ),
        migrations.AlterModelTable(
            name='importrow',
            table=None,
        ),
        migrations.AlterModelTable(
            name='ingreso',
            table=None,
        ),
        migrations.AlterModelTable(
            name='notificacion',
            table=None,
        ),
        migrations.AlterModelTable(
            name='pendiente',
            table=None,
        ),
        migrations.AlterModelTable(
            name='producto',
            table=None,
        ),
        migrations.AlterModelTable(
            name='retiro',
            table=None,
        ),
        migrations.AlterModelTable(
            name='usuario',
            table=None,
        ),
    ]
