# Generated by Django 5.2.4 on 2025-07-12 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_usuariocargo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingreso',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Retiro',
        ),
    ]
