# Generated by Django 5.2.4 on 2025-07-12 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_ingreso_delete_producto_delete_retiro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField()),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ingreso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras', models.CharField(max_length=20, unique=True)),
                ('centro_costo', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('stock_actual', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('precio', models.FloatField()),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Retiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField()),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'retiro',
                'managed': False,
            },
        ),
    ]
