# Generated by Django 5.2.4 on 2026-03-18 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_familia_to_gerencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='gerencia',
            field=models.ForeignKey(blank=True, help_text='Gerencia o subgerencia a la que pertenece el producto.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='app.gerencia'),
        ),
    ]
